name: Deploy Static HTML

on:
  push:
    branches:
      - main  # Troque "main" pelo nome do branch principal, se for diferente.

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # O diretório onde estão os arquivos HTML.
